### ISSUE TITLE
Copying with shortcut does not work anymore

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snomed-interaction-components#51]
Ctrl-c does no longer copy concept id + term

**Comment by rorydavidson** [comment]
Thanks, we'll look into it and get it fixed.

**Comment by rorydavidson** [comment]
This has now been fixed and deployed, as part of commit https://github.com/IHTSDO/snomed-interaction-components/commit/f4fa16bb197ea26790f55936a5710ff0fef1b552

**Comment by danka74** [comment]
A very minor stylistic change ;) now there is a space between id and vertical bar but no spaces between vertical bars and term. Suggest to have consistent use of spaces, either no spaces or spaces, don't really mind which.
Example: 404684003 |Clinical finding (finding)|
So, either
e.clipboardData.setData('text/plain', firstMatch.conceptId + " | " + firstMatch.defaultTerm + " |");
or
e.clipboardData.setData('text/plain', firstMatch.conceptId + "|" + firstMatch.defaultTerm + "|");
/Daniel

**Comment by rorydavidson** [comment]
And change made and deployed in release v1.36.1. Went with your first version.
